### ISSUE TITLE
How to add crossorigin="use-credentials"

### ISSUE THREAD

**Issue by tschoartschi** [zonkyio/ember-web-app#115]
We have our web app behind a http basic auth, therefore we need to add `crossorigin="use-credentials"` to the `<link rel="manifest" href="/manifest.json">` Tag.

For more details about manifest and http basic auth you can visit the link: https://thatemil.com/blog/2018/02/21/pwa-basic-auth/

**Comment by bobisjan** [comment]
Hi 👋,

thanks for opening the issue, adding the `crossorigin` parameter into add-on should work fine.

**Comment by tschoartschi** [comment]
@bobisjan thanks for the feedback 😃 do you have any idea when this could be included?

**Comment by bobisjan** [comment]
@tschoartschi, will take a look during this weekend 🙂.

**Comment by tschoartschi** [comment]
@bobisjan thanks for the quick fix 😃 I'll have a look on it beginning of next week and I'll give you feedback

**Comment by bobisjan** [comment]
@tschoartschi, it's in `master`, you can test and report back if something went wrong ☺️.
