### ISSUE TITLE
Wrong link tag attribute in documentation

### ISSUE THREAD

**Issue by oscarni** [zonkyio/ember-web-app#222]
Shouldn't it be `href` instead of `src` in the link-tag you add to index?
https://zonkyio.github.io/ember-web-app/docs/getting-started/installation

Now:
```
<link rel="manifest" src="{{rootURL}}manifest.webmanifest" />
```

Should be:

```
<link rel="manifest" href="{{rootURL}}manifest.webmanifest" />
```

See https://developer.mozilla.org/en-US/docs/Web/Manifest#Deploying_a_manifest_with_the_link_tag

**Comment by bobisjan** [comment]
@oscarni thanks for report, and yes, it should be `href` instead.
