### ISSUE TITLE
Can't push my manifest.webmanifest to S3 using ember-cli-deploy

### ISSUE THREAD

**Issue by olenderhub** [zonkyio/ember-web-app#261]
Locally I have:

http://localhost:4200/manifest.webmanifest

I want to deploy manifest.webmanifest to S3 similar like I deployed it with `ember-cli-deploy-manifest`

with this addon, it's generated me `manifest.txt` on my S3. What can I do to export in the same way. manifest.webmanifest there? 
I have Rails application and it renders me Ember inside, so I can't use Ember public folder on Staging. I can only use the Rails public folder for this. one solution that I see here is to deploy directly manifest to S3 and change the path for it.

btw. browserconfig.xml is uploaded correctly to S3

my addons:

```
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-manifest": "^1.1.0",
    "ember-cli-deploy-redis": "^1.0.2",
    "ember-cli-deploy-revision-data": "^1.0.0",
    "ember-cli-deploy-s3": "^1.1.0",
    "ember-web-app¦: ¦^3.0.0-beta.4"
```

not sure if this is issue more to `ember-web-app` or `ember-cli-deploy`

**Comment by bobisjan** [comment]
Hi 👋,

`ember-web-app` does not participate in deployment process, so you have to explicitly put `webmanifest` extension to the `ember-cli-deploy-s3`'s `filePattern` configuration.

The reason for already uploaded `browserconfig.xml` comes from the [default configuration](https://github.com/ember-cli-deploy/ember-cli-deploy-s3/blob/master/index.js#L19), which includes `xml` extension.

**Comment by olenderhub** [comment]
@bobisjan thank you so much for this explanation! :)
