### ISSUE TITLE
Why not integrate a somewhat dynamic service worker generator?

### ISSUE THREAD

**Issue by jfrux** [zonkyio/ember-web-app#290]
I would think it could be slick to be able to toggle on caching of assets for offline features.
Manifest is like 50% of converting an app to a PWA... still have to have a service worker for it to be a true PWA... no?

**Comment by bobisjan** [comment]
Thanks for opening an issue, I agree that having only `webmanifest` file is just a part of PWA.

There is already an existing solution http://ember-service-worker.com/ with its plugin approach for service worker integration.

What about updating documentation about using `ember-service-worker`?

**Comment by jfrux** [comment]
I’m terribly sorry... I’ve used ember service worker briefly in the past and completely forgot about it!!
It was a very long day and I forgot about this.

Thank you for your contributions to the community!

<3 jfrux

**Comment by bobisjan** [comment]
No worries, I'm going to close this issue, but I've opened issue to make documentation better to understand the role of this add-on in PWA, #292.
