### ISSUE TITLE
Doc link not working

### ISSUE THREAD

**Issue by MichalBryxi** [zonkyio/ember-web-app#44]
The [README.md](https://github.com/zonkyio/ember-web-app) links to page that does not work: https://zonkyio.github.io/ember-web-app/

**Comment by bobisjan** [comment]
@MichalBryxi thanks for the report, I'm currently in the middle of the `docs` migration 🚀.

**Comment by MichalBryxi** [comment]
No worries @bobisjan. Just stumbled upon this while debugging some warning in my project. Hope everything will go well :+1:

**Comment by bobisjan** [comment]
@MichalBryxi, in the meantime you can use this link https://zonkyio.github.io/ember-web-app/versions/addon-docs/docs.

**Comment by bobisjan** [comment]
Release [v3.0.0](https://github.com/zonkyio/ember-web-app/releases/tag/v3.0.0) is out, the documentation is now live at https://zonkyio.github.io/ember-web-app.
