### ISSUE TITLE
Remove `ember-web-app-rename` removal from after install hook

### ISSUE THREAD

**Issue by bobisjan** [zonkyio/ember-web-app#47]
Is this still needed to be handled here? 🤔

https://github.com/zonkyio/ember-web-app/blob/master/blueprints/ember-web-app/index.js#L13

Should be https://github.com/san650/ember-web-app-rename deprecated itself and users will be notified to update `ember-web-app` from that add-on?

/cc @san650

**Comment by san650** [comment]
@bobisjan I think it's safe now to remove that logic. I'll deprecate `ember-web-app-rename`, good call.
