### ISSUE TITLE
How to link web app on current path?

### ISSUE THREAD

**Issue by yaxinr** [zonkyio/ember-web-app#78]
I want to get few shortcuts-web-apps on few url paths?
Maybe:
example.com/
example.com/new-task
example.com/tasks
...

How change StartUrl at runtime?

**Comment by bobisjan** [comment]
Hi @yaxinr,

I'm not sure if I understand correctly, you can have separate manifests per path in general, but this would end up with multiple applications on the home screen, which is not a _common_ thing to have multiple icons for a single application.

One possible solution might be to show some screen (aka "modal") at `start_url` with links to the common routes, but it depends on your use case.

Hope this helps ☺️.

**Comment by bobisjan** [comment]
Closing now, but @yaxinr feel free to reopen if required.
